# -*- coding: utf-8 -*-
"""
Datos de los guiones de AE of Miami.
Cada guion es un dict con:
  numero, titulo, pilar, duracion,
  planos: lista de tuplas (label, descripcion, dialogo_o_lista_de_lineas, transicion_antes_opcional)
  hooks: lista de opciones de hook (la primera suele ser la del cliente)
  ctas: lista de opciones de CTA (la primera suele ser la del cliente)
  notas: string o lista de strings con notas de producción
  hook_planos / cta_planos: string descriptivo de a qué planos aplica (para el encabezado del PDF)
"""

GUIONES = [
    {
        "numero": 1,
        "titulo": "Overthinking Has a Cost",
        "pilar": "Urgencia",
        "duracion": "~30s",
        "planos": [
            ("PLANO 1", "Abierto — de pie junto al carro, mirando a cámara", "Este cliente venía manejando desde otro estado..."),
            ("PLANO 2", "Corte (whip-pan) a otro ángulo del mismo carro, señalándolo", "...para ver este carro."),
            ("PLANO 3", "Corte — caminando por el lote", "Le dijimos que lo reservara antes de viajar."),
            ("PLANO 4", "Corte — junto al carro otra vez", "Pero prefirió venir a verlo primero."),
            ("PLANO 5", "Corte — acercamiento a plano medio, arranca el beat de tensión", "Unas horas antes de llegar..."),
            ("PLANO 6", "Corte más cerrado (el más cercano del video) — remate", "...alguien más lo reservó."),
            ("PLANO 7", "Corte — plano medio, tono de conclusión", "Esperar demasiado tiene un costo."),
            ("PLANO 8", "Corte — plano fijo a cámara, arranca el CTA", "Antes de hacer el viaje, confirma disponibilidad con ventas..."),
            ("PLANO 9", "Mismo plano o corte sutil de cierre — remate final", "...y pregunta cómo puedes reservarlo."),
        ],
        "hooks": [
            "Este cliente venía manejando desde otro estado... para ver este carro. / ...unas horas antes de llegar, alguien más lo reservó.",
            "Manejó horas desde otro estado para ver este carro... / ...y no llegó a tiempo.",
            "Le dijimos que lo reservara antes de viajar. / No lo hizo.",
            "A veces la diferencia entre quedarte con el carro y perderlo... / ...son un par de horas.",
            "Este carro ya tenía comprador... / ...antes de que el primero llegara a verlo.",
        ],
        "ctas": [
            "Antes de hacer el viaje, confirma disponibilidad con ventas... / ...y pregunta cómo puedes reservarlo.",
            "No manejes a ciegas. / Llama antes y asegura el carro.",
            "Un mensaje a ventas te puede ahorrar el viaje... / ...o asegurarte el carro.",
            "Antes de venir... / ...pregúntanos cómo reservarlo.",
            "Habla con ventas primero. / Después haz el viaje.",
        ],
        "notas": "si eliges un hook que ya adelanta “lo reservaron” (opciones 1 o 5), quita esa misma frase de los Planos 5–6 para no repetirla.",
        "hook_planos": "Planos 1–2",
        "cta_planos": "Planos 8–9",
    },
    {
        "numero": 2,
        "titulo": "Today I Set the Prices",
        "pilar": "Urgencia",
        "duracion": "~30s",
        "planos": [
            ("PLANO 1", "Ella en cuadro, sin gorra (“jefa”)", "Hoy los precios los pongo yo."),
            ("PLANO 2", "Parada justo frente al Carro 1, sin gorra", "¿Cuál es este?", "[Paneo rápido con blur — camina hacia el Carro 1]"),
            ("PLANO 3", "Mismo lugar, ahora con gorra puesta (“vendedora”)", "Toyota Tacoma 2020.", "[Paneo con blur — durante el blur se pone la gorra: el cambio queda escondido en el movimiento]"),
            ("PLANO 4", "Vuelve a ser “jefa” (sin gorra)", "Perfecto... ponla en $_____.", "[Paneo con blur — se quita la gorra en el blur]"),
            ("PLANO 5", "Frente al Carro 2, sin gorra", "¿Y este?", "[Paneo con blur — camina al Carro 2]"),
            ("PLANO 6", "Con gorra", "Honda Civic 2019.", "[Paneo con blur — se pone la gorra]"),
            ("PLANO 7", "Sin gorra", "Esta... en $_____.", "[Paneo con blur — se quita la gorra]"),
            ("PLANO 8", "Frente al Carro 3 — mismo mecanismo pero comprimido y más rápido (gorra puesta/quitada más veloz, paneos más cortos)",
                ["¿Este? (sin gorra)", "[Modelo]. (con gorra)", "$_____. Siguiente. (sin gorra)"],
                "[Paneo con blur — camina al Carro 3]"),
            ("PLANO 9", "Cierre fijo a cámara, sin gorra, sin paneo", "¿Cuál de estos te llevarías? Escríbenos y confirma si todavía está disponible."),
        ],
        "hooks": [
            "Hoy los precios los pongo yo.",
            "Hoy yo mando aquí. Vamos a poner precios.",
            "Se me ocurrió jugar a ser la jefa por un día.",
            "Nadie me dijo que no podía poner los precios hoy.",
            "Hoy decido yo cuánto cuesta cada carro.",
        ],
        "ctas": [
            "¿Cuál de estos te llevarías? Escríbenos y confirma si todavía está disponible.",
            "Dinos cuál te gustó y te confirmamos si sigue disponible.",
            "¿Viste uno que te gustó? Escríbenos antes de que se acabe el precio de hoy.",
            "Comenta cuál elegirías. Nosotros te decimos si sigue aquí.",
            "Escríbenos cuál quieres. Y ojalá el precio siga en pie.",
        ],
        "notas": [
            "el gag de doble personaje (jefa/vendedora) se resuelve poniéndose y quitándose la gorra durante el blur del paneo — es el cambio más rápido posible y aprovecha que ya usa gorra de marca en otros videos.",
            "si en cámara el cambio no alcanza a esconderse bien en el blur, la alternativa es grabar las líneas de “vendedora” por separado (todas seguidas, con gorra) y las de “jefa” por separado, y editarlas intercaladas con el mismo efecto de paneo simulado en post.",
            "necesita 3 carros distintos ya elegidos (y sus precios reales) antes de grabar.",
        ],
        "hook_planos": "Plano 1",
        "cta_planos": "Plano 9",
    },
    {
        "numero": 3,
        "titulo": "Clean, Salvage or Junk?",
        "pilar": "Educativo",
        "duracion": "~30s",
        "planos": [
            ("PLANO 1", "Ella de pie, gesto de contar con los dedos (3 conceptos)", "Clean, Salvage y Junk..."),
            ("PLANO 2", "Mismo plano, remata la pregunta", "...¿sabes realmente cuál es la diferencia?"),
            ("PLANO 3", "Junto al Carro 1 (Clean Title)", "Este es Clean Title.", "[Paneo/corte al primer carro de ejemplo]"),
            ("PLANO 4", "Sigue en el mismo carro, explica", "Nunca tuvo daño reportado. Es como comprar cualquier carro normal."),
            ("PLANO 5", "Junto al Carro 2 (Salvage Title)", "Este es Salvage.", "[Paneo/corte al segundo carro]"),
            ("PLANO 6", "Explica — aquí va el punto clave que rompe el mito", "Tuvo daño, se reparó y pasó inspección. Eso no significa que sea mala compra."),
            ("PLANO 7", "Junto al Carro 3 (Junk Title)", "Y este es Junk.", "[Paneo/corte al tercer carro]"),
            ("PLANO 8", "Explica", "Este ya no se puede registrar para manejar. Es solo para piezas."),
            ("PLANO 9", "Corte a plano medio, tono de conclusión (conecta con el mensaje de marca: confianza)", "Lo importante no es el título. Es entender el daño y hacer los números."),
            ("PLANO 10", "Cierre fijo a cámara", "Antes de comprar, pregunta por el título, revisa el daño y asegúrate de entender exactamente qué estás comprando."),
        ],
        "hooks": [
            "Clean, Salvage y Junk... / ...¿sabes realmente cuál es la diferencia?",
            "Estas tres palabras espantan a mucha gente... / ...y la mayoría ni sabe lo que significan.",
            "Salvage no es lo que la gente piensa. / Te explico con carros reales.",
            "¿Clean, Salvage o Junk? / La diferencia no es la que crees.",
            "Hay un título que la gente evita sin saber por qué. / Vamos a aclararlo.",
        ],
        "ctas": [
            "Antes de comprar, pregunta por el título, revisa el daño y asegúrate de entender exactamente qué estás comprando.",
            "No le tengas miedo al título. Pregunta, revisa, y decide con información real.",
            "Pregunta por el título, mira el daño con tus propios ojos, y saca la cuenta.",
            "El título no te dice todo. Ven y te mostramos exactamente qué estás comprando.",
            "Antes de decidir, pide ver el daño y el reporte. Así no hay sorpresas.",
        ],
        "notas": [
            "necesita 3 carros reales ya identificados con cada tipo de título (Clean/Salvage/Junk) antes de grabar.",
            "verificar con el cliente los datos exactos sobre registro/aseguramiento de cada tipo de título antes de grabar — es contenido educativo que construye confianza, pero un dato legal incorrecto puede generar un problema de reputación.",
        ],
        "hook_planos": "Planos 1–2",
        "cta_planos": "Plano 10",
    },
    {
        "numero": 4,
        "titulo": "R U Guys Real??",
        "pilar": "Confianza",
        "duracion": "~35-40s",
        "estado": "Pendiente de grabar",
        "planos": [
            ("PLANO 1", "Ella mirando directo a cámara, tono personal, hook completo de un tirón", "Muchos preguntan si de verdad somos reales... así que ven, te voy a enseñar AE OF MIAMI por dentro."),
            ("PLANO 2", "Área de subastas", "Aquí es donde compramos los carros, en subasta, todos los días. Este proceso es el que nos permite tener tanta variedad en el lote.", "[Corte — caminando hacia la primera área]"),
            ("PLANO 3", "Lote / inventario", "Y este es nuestro inventario. Cada carro que ves aquí pasó por nuestras manos antes de llegar a este punto.", "[Corte]"),
            ("PLANO 4", "Taller, mecánicos y electricistas trabajando", "Aquí están nuestros mecánicos y nuestro equipo eléctrico, trabajando en los carros todos los días. Esto no se arregla solo.", "[Corte]"),
            ("PLANO 5", "Oficina / marketing", "Y aquí está el equipo que hace que todo esto llegue a tus redes: marketing, ventas, oficina. Gente real, trabajando todos los días.", "[Corte]"),
            ("PLANO 6", "Plano medio, tono firme, mensaje central", "Sí somos reales. Sí existimos. Aquí estamos, y estos son nuestros carros.", "[Corte, vuelve a ella]"),
            ("PLANO 7", "Cierre fijo a cámara", "Visita aeofmiami.com, revisa nuestro inventario y habla directamente con uno de nuestros vendedores."),
        ],
        "hooks": [
            "Muchos preguntan si de verdad somos reales... así que ven, te voy a enseñar AE OF MIAMI por dentro.",
            "¿Ustedes son reales o esto es una estafa? Nos preguntan esto todos los días. Te lo voy a mostrar.",
            "Sí, hay gente que cree que esto es un fraude. Ven, te enseño por qué no lo es.",
            "Detrás de esta página hay algo que casi nadie ve. Te lo muestro.",
            "No somos solo una página. Ven a ver todo lo que hay detrás.",
        ],
        "ctas": [
            "Visita aeofmiami.com, revisa nuestro inventario y habla directamente con uno de nuestros vendedores.",
            "Entra a aeofmiami.com y compruébalo tú mismo.",
            "El inventario está en aeofmiami.com. Ven o escríbenos — nosotros somos reales.",
            "Revisa el inventario, habla con nosotros, y compruébalo con tus propios ojos.",
            "Aeofmiami.com. Ahí está todo. Y aquí estamos nosotros.",
        ],
        "notas": [
            "con frases más largas por parada, este guion corre 35-40 segundos en vez de 30. Para dejarlo en 30s justos, fusionar el Plano 4 y 5 en una sola parada, o quitar una de las 5 áreas.",
            "necesita coordinación previa con cada equipo (subastas, mecánica, eléctrico, marketing, oficina) para que estén trabajando naturalmente cuando pase la cámara — no debe sentirse posado.",
        ],
        "hook_planos": "Plano 1",
        "cta_planos": "Plano 7",
    },
    {
        "numero": 5,
        "titulo": "Can I Even Get This Financed?",
        "pilar": "Educativo / Objeción",
        "duracion": "~30s",
        "planos": [
            ("PLANO 1", "Ella mirando a cámara, tono directo", "La pregunta que más nos hacen no es sobre los carros..."),
            ("PLANO 2", "Remata", "...es sobre cómo se pagan."),
            ("PLANO 3", "Corte, tono informativo, sin rodeos", "No financiamos.", "[Corte]"),
            ("PLANO 4", "Sigue explicando", "Trabajamos con cash, cheque de caja o transferencia verificada."),
            ("PLANO 5", "Gira el argumento (convierte la limitación en confianza)", "¿Por qué? Porque así no hay intereses escondidos."),
            ("PLANO 6", "Remata el argumento", "Ni sorpresas en el papeleo."),
            ("PLANO 7", "Tono de cierre", "El precio que ves... es el precio real."),
            ("PLANO 8", "Cierre fijo a cámara", "Escríbenos y te explicamos exactamente cómo funciona el pago, sin sorpresas."),
        ],
        "hooks": [
            "La pregunta que más nos hacen no es sobre los carros... / ...es sobre cómo se pagan.",
            "No, no financiamos. / Y esa es la mejor parte.",
            "¿Cómo se paga aquí? / Te lo explico en 20 segundos.",
            "Hay algo que preferimos decirte antes de que vengas... / ...sobre cómo funciona el pago.",
            "Esto no es un banco. / Y por eso el precio no tiene sorpresas.",
        ],
        "ctas": [
            "Escríbenos y te explicamos exactamente cómo funciona el pago, sin sorpresas.",
            "Pregúntanos antes de venir. Así no hay sorpresas cuando llegues.",
            "Un mensaje y te decimos exactamente qué necesitas traer.",
            "Escríbenos. El precio que ves es el que pagas.",
            "Habla con ventas y confirma las opciones de pago antes de venir.",
        ],
        "notas": "verificar con el cliente los métodos de pago exactos aceptados (cash, cheque de caja, transferencia) antes de grabar, para no afirmar algo que no sea política real del negocio.",
        "hook_planos": "Planos 1–2",
        "cta_planos": "Plano 8",
    },
    {
        "numero": 6,
        "titulo": "Does It Even Turn On?",
        "pilar": "Confianza / Educativo",
        "duracion": "~30s",
        "planos": [
            ("PLANO 1", "Ella junto a un carro salvage, tono directo", "La primera pregunta que casi todos hacen..."),
            ("PLANO 2", "Remata", "...¿esto siquiera enciende?"),
            ("PLANO 3", "Se acerca a la puerta/llave", "Te lo muestro.", "[Corte]"),
            ("PLANO 4", "Plano cerrado a la llave girando", "Mira."),
            ("PLANO 5", "El carro enciende, reacción natural de ella", "Ahí está.", None),
            ("PLANO 6", "Explica el daño real que tuvo el carro", "Este tuvo un golpe en el frente. Nada del motor.", "[Corte]"),
            ("PLANO 7", "Tono de conclusión, matiza el mensaje", "No todos los salvage son iguales. Por eso hay que ver cada uno con calma."),
            ("PLANO 8", "Cierre fijo a cámara", "Ven, lo prendemos frente a ti antes de que decidas."),
        ],
        "hooks": [
            "La primera pregunta que casi todos hacen... / ...¿esto siquiera enciende?",
            "¿Un carro salvage enciende? / Te lo muestro ahora mismo.",
            "Esto es lo primero que reviso con cualquier comprador. / Que encienda.",
            "No te voy a decir que sí. / Te lo voy a mostrar.",
            "Esta es la pregunta que resuelve todo lo demás. / ¿Enciende?",
        ],
        "ctas": [
            "Ven, lo prendemos frente a ti antes de que decidas.",
            "No lo compres sin verlo encender primero. Ven al lote.",
            "Pruébalo tú mismo. Ven y lo encendemos juntos.",
            "Antes de decidir, ven a escucharlo prender.",
            "Si tienes dudas de otro carro, ven y lo probamos igual.",
        ],
        "notas": "necesita un carro real, con llave a mano, que efectivamente encienda sin problema — idealmente uno con daño cosmético visible (para que el contraste “se ve mal pero prende bien” tenga fuerza), confirmado de antemano por el equipo mecánico.",
        "hook_planos": "Planos 1–2",
        "cta_planos": "Plano 8",
    },
    {
        "numero": 7,
        "titulo": "Recorrido del Dealer (B-roll / Paneo musical)",
        "pilar": "Variedad / Branding — sin diálogo",
        "duracion": "~20-30s",
        "estado": "Placeholder — falta desarrollar a detalle",
        "planos": [
            ("PLANO 1", "Toma amplia del letrero AE OF MIAMI", None),
            ("PLANO 2", "Paneo por el lote, fila de carros", None),
            ("PLANO 3", "Detalle: alguien caminando entre los carros / manos revisando un carro", None),
            ("PLANO 4", "Taller — mecánicos trabajando", None),
            ("PLANO 5", "Área eléctrica", None),
            ("PLANO 6", "Oficina / equipo", None),
            ("PLANO 7", "Cierre — carro arrancando o saliendo del lote, cámara lenta", None),
            ("PLANO 8", "Card de cierre con texto en pantalla", "aeofmiami.com"),
        ],
        "hooks": [],
        "ctas": [],
        "notas": [
            "Placeholder — este video es solo un recordatorio para el conteo, todavía falta desarrollarlo a detalle (selección final de tomas, música, duración exacta del edit).",
            "100% visual, sin diálogo ni voz en off — es un edit con música. El único texto en pantalla es el card de cierre.",
            "variante sugerida (ref. reel \u201cCuando el vendedor empieza a grabar un audio\u201d): en vez de tomas sueltas, seguir a alguien del equipo que recorre todo el dealer grabando una nota de voz larguísima — se sienta en un carro, se mete en el maletero, pasa por el taller, sale a la calle. Sigue sin diálogo (solo música + ese texto en pantalla), pero le da un hook y un chiste al recorrido.",
        ],
    },
    {
        "numero": 8,
        "titulo": "Do You Guys Negotiate?",
        "pilar": "Objeción / Confianza",
        "duracion": "~30s",
        "estado": "Draft — pendiente de correcciones",
        "planos": [
            ("PLANO 1", "Ella, tono casi cómplice", "La pregunta que nadie quiere hacer en voz alta..."),
            ("PLANO 2", "Remata", "...¿se puede negociar el precio?"),
            ("PLANO 3", "Corte, respuesta directa", "A veces sí.", "[Corte]"),
            ("PLANO 4", "Matiza", "Depende del carro, de cuánto tiempo lleva en el lote, y de cómo llegues a preguntar."),
            ("PLANO 5", "Consejo práctico", "Lo peor que puedes hacer es no preguntar."),
            ("PLANO 6", "Cierre, tono cercano", "Ven, pregunta, y hablamos como personas normales."),
            ("PLANO 7", "CTA", "Escríbenos antes de venir y te decimos si ese carro en específico tiene margen."),
        ],
        "hooks": [
            "La pregunta que nadie quiere hacer en voz alta... / ...¿se puede negociar el precio?",
            "¿Se puede bajar el precio? / Depende. Te explico de qué.",
            "Esto no es un mercado persa... / ...pero tampoco es un precio tallado en piedra.",
            "Nadie pregunta esto directamente... / ...así que te ahorro la pena.",
            "¿Regatear funciona aquí? / A veces. Aquí está el cuándo.",
        ],
        "ctas": [
            "Escríbenos antes de venir y te decimos si ese carro en específico tiene margen.",
            "Pregunta. En el peor de los casos, la respuesta es no.",
            "Ven con la pregunta lista. No muerde.",
            "Escríbenos el carro que te interesa y hablamos de números.",
            "No pierdes nada con preguntar. Ven y hazlo.",
        ],
        "notas": "verificar con el cliente qué tan real/frecuente es la negociación antes de grabar — tema delicado si el negocio prefiere mantener precios fijos; ajustar el mensaje a su política real.",
        "hook_planos": "Planos 1–2",
        "cta_planos": "Plano 7",
    },
    {
        "numero": 9,
        "titulo": "Can Someone Pick It Up for Me?",
        "pilar": "Educativo / Alcance",
        "duracion": "~30s",
        "estado": "Draft — pendiente de correcciones",
        "planos": [
            ("PLANO 1", "Hook", "No todo el mundo puede venir hasta Miami..."),
            ("PLANO 2", "Remata", "...y aun así nos compran carros."),
            ("PLANO 3", "Explica", "Puedes mandar a alguien de confianza a recogerlo por ti.", "[Corte]"),
            ("PLANO 4", "Sigue", "O coordinamos el envío directo a tu puerta."),
            ("PLANO 5", "Refuerza confianza", "De cualquier forma, te mostramos todo del carro antes de pagar."),
            ("PLANO 6", "Cierre", "No importa dónde estés. Hay una forma de hacerlo llegar."),
            ("PLANO 7", "CTA", "Escríbenos tu ciudad y te decimos la opción más fácil para ti."),
        ],
        "hooks": [
            "No todo el mundo puede venir hasta Miami... / ...y aun así nos compran carros.",
            "¿Vives lejos? / Eso no es un problema aquí.",
            "No necesitas estar en Miami para comprar en Miami.",
            "Alguien más puede recoger tu carro por ti. / Así de simple.",
            "La distancia no es excusa. / Te explico cómo funciona.",
        ],
        "ctas": [
            "Escríbenos tu ciudad y te decimos la opción más fácil para ti.",
            "No importa dónde estés, pregúntanos cómo coordinarlo.",
            "Dinos a dónde necesitas que llegue, y vemos cómo hacerlo.",
            "Escríbenos antes de descartar el carro por la distancia.",
            "Pregunta primero. La logística la resolvemos nosotros.",
        ],
        "notas": "verificar con el cliente los requisitos legales exactos para que un tercero recoja el carro a nombre del comprador (poder, autorización, etc.) antes de grabar.",
        "hook_planos": "Planos 1–2",
        "cta_planos": "Plano 7",
    },
    {
        "numero": 10,
        "titulo": "De que te guste hasta que te lo llevas",
        "pilar": "Educativo",
        "duracion": "~30s",
        "estado": "Draft — pendiente de correcciones",
        "planos": [
            ("PLANO 1", "Ella sentada siempre en el mismo lugar (silla en el lote u oficina), plano medio fijo, mirando a cámara. Este plano es el \u201cancla\u201d al que se vuelve entre cada paso", "Hoy me llevo mi carro. Vente conmigo."),
            ("PLANO 2", "Llegando al lote, caminando entre los carros", "Lo vi en la página el martes...", "[Corte]"),
            ("PLANO 3", "Parada frente al carro, lo toca", "...y hoy lo vine a ver en persona.", "[Corte]"),
            ("PLANO 4", "Vuelve al ancla (sentada, a cámara)", "Primero: revisarlo todo.", "[Corte]"),
            ("PLANO 5", "Inspección: le muestran el golpe, abren el capó", "Me enseñaron el golpe, el motor, todo.", "[Corte]"),
            ("PLANO 6", "Ancla", "Después, el título.", "[Corte]"),
            ("PLANO 7", "Detalle: el título en la mano", "Salvage, reparado. Sin sorpresas.", "[Corte]"),
            ("PLANO 8", "Ancla", "Luego el pago...", "[Corte]"),
            ("PLANO 9", "Detalle: firma de papeles", "...y firmo.", "[Corte]"),
            ("PLANO 10", "Detalle: le entregan las llaves en la mano, reacción", "Y ahora sí...", "[Corte]"),
            ("PLANO 11", "Plano abierto: sale manejando del lote, la música sube. Es el clímax del video", "...es mío.", "[Corte]"),
            ("PLANO 12", "Cierre fijo a cámara (o card de cierre)", "Así se ve todo el proceso. Ven y vívelo tú mismo."),
        ],
        "hooks": [
            "Hoy me llevo mi carro. Vente conmigo.",
            "Vi este carro el martes. Hoy es mío.",
            "Acompáñame a comprar mi carro, de principio a fin.",
            "Desde que lo vi en la página hasta que me lo llevé. Todo el proceso.",
            "Así es comprar un carro en AE of Miami. Sin cortes raros, sin letra pequeña.",
        ],
        "ctas": [
            "Así se ve todo el proceso. Ven y vívelo tú mismo.",
            "Así de simple es. Ven cuando quieras empezar.",
            "Ya sabes los pasos. Ahora falta el carro — ven a elegirlo.",
            "Nada escondido, nada complicado. Ven a comprobarlo.",
            "¿Cuál sería el tuyo? Escríbenos y empezamos.",
        ],
        "notas": [
            "estructura tomada del reel de referencia de proceso (el de la novia que se prepara): una persona narra a cámara siempre desde el mismo lugar, y entre cada frase se salta al siguiente paso. El final tiene que sentirse como el gran momento (sale manejando), igual que el baile en la referencia.",
            "puede hacerlo Daniela actuando como compradora, o un cliente real que esté comprando ese día (con su permiso) — un cliente real le da mucha más credibilidad.",
            "lo que se diga del pago y del título debe coincidir con la política real (pago directo, sin financiamiento) y con el título real de ese carro.",
        ],
        "hook_planos": "Plano 1",
        "cta_planos": "Plano 12",
    },
    {
        "numero": 11,
        "titulo": "El Trato",
        "pilar": "Entretenimiento / Urgencia (trend)",
        "duracion": "~20s",
        "estado": "Draft — pendiente de correcciones",
        "planos": [
            ("PLANO 1", "Daniela sentada en una silla de oficina en medio del lote, lentes de sol, dos del equipo de pie detrás con los brazos cruzados (estilo mafia)", "Yo te tengo un trato."),
            ("PLANO 2", "Plano abierto, el letrero de AE of Miami detrás", "Yo sé que tú necesitas un carro...", "[Corte]"),
            ("PLANO 3", "Mismo plano, ella se encoge de hombros", "...pero no tienes carro."),
            ("PLANO 4", "Corte, ella señala el lote a su espalda", "Yo tengo carros...", "[Corte]"),
            ("PLANO 5", "Plano más cerrado, gesto de \u201cpásame la plata\u201d", "Tú me das el pago...", "[Corte]"),
            ("PLANO 6", "Uno del equipo le entrega unas llaves a cámara", "...y yo te doy el carro.", "[Corte]"),
            ("PLANO 7", "Los tres caminan hacia cámara, se quitan los lentes", "Y así todos contentos.", "[Corte]"),
            ("PLANO 8", "Toma del letrero de AE of Miami, texto en pantalla", "En AE of Miami."),
        ],
        "hooks": [
            "Yo te tengo un trato.",
            "Te tengo una propuesta que no vas a poder rechazar.",
            "Siéntate. Vamos a hablar de negocios.",
            "Esto es lo más simple que vas a escuchar hoy.",
            "Tengo una oferta. Escucha bien.",
        ],
        "ctas": [
            "Escríbenos y cerramos el trato.",
            "¿Tenemos un trato? Escríbenos.",
            "Trato hecho. Ven al lote.",
            "Elige tu carro y hablamos.",
            "Así de simple. Te esperamos en AE of Miami.",
        ],
        "notas": [
            "adaptación del trend de la referencia (Toyota de Hollywood). Es un video de humor, pero el chiste refuerza algo real de la marca: el pago es directo, sin financiamiento — \u201ctú me das el pago, yo te doy el carro\u201d.",
            "si usan el audio original del trend, que sea desde la biblioteca de audio de Instagram (no descargado y vuelto a subir), para que quede licenciado en la plataforma. Si no, se graba con la voz de Daniela siguiendo la misma cadencia.",
            "en la referencia dicen \u201cpero no tengo plata\u201d; aquí se cambió para que la marca no quede como un negocio que necesita vender a toda costa.",
            "vestuario: lentes de sol para los tres, ropa en negro y blanco.",
        ],
        "hook_planos": "Plano 1",
        "cta_planos": "Plano 8",
    },
    {
        "numero": 12,
        "titulo": "¿Quién sabe de esto?",
        "pilar": "Confianza / Entretenimiento",
        "duracion": "~30-35s",
        "estado": "Draft — pendiente de correcciones",
        "planos": [
            ("PLANO 1", "Un cliente frente a un carro, Daniela atendiéndolo", "¿Y esto me lo pueden enviar a Colombia? (cliente)"),
            ("PLANO 2", "Daniela, pausa corta, sonrisa", "Eso te lo dice Carlos. Ya vengo."),
            ("PLANO 3", "PLANO SECUENCIA, sin cortes: la cámara sigue a Daniela de espaldas mientras recorre todo el dealer buscándolo — lote, taller, área eléctrica, oficina, subastas. En cada área pregunta y alguien le señala otro lado",
                ["¿Y Carlos? (Daniela)", "¡En el taller! (alguien del equipo)", "¿Carlos? (Daniela)", "Se fue para la oficina. (alguien del equipo)"]),
            ("PLANO 4", "Lo encuentra y lo jala del brazo de vuelta", "Te necesitan."),
            ("PLANO 5", "Llegan donde el cliente, Daniela sin aire", "Sí, a Colombia enviamos. Te explico cómo funciona. (Carlos)"),
            ("PLANO 6", "Cierre: Daniela a cámara", "Aquí cada pregunta tiene a alguien que la sabe responder."),
        ],
        "hooks": [
            "¿Y esto me lo pueden enviar a Colombia? / Eso te lo dice Carlos. Ya vengo.",
            "Texto en pantalla: \u201cCuando el cliente pregunta algo que solo sabe una persona\u201d",
            "POV: preguntaste algo muy específico.",
            "La pregunta era fácil. Encontrar a Carlos, no.",
            "Ya vengo... (y arranca a correr)",
        ],
        "ctas": [
            "¿Tienes una pregunta así de específica? Escríbenos.",
            "Pregunta lo que quieras. Siempre hay alguien que sabe.",
            "Escríbenos tu duda y te responde quien sabe.",
            "Aquí nadie te responde \u201cno sé\u201d. Escríbenos.",
            "Ven con tus preguntas. Nosotros buscamos a Carlos.",
        ],
        "notas": [
            "combina dos referencias: el reel de la tienda de cartas (ella recorre todo el lugar en una sola toma buscando a su compañero) y el de \u201cbuscando a George\u201d. Del segundo no se tomó el chiste (el vendedor miente diciendo que George murió) porque deja al equipo como poco confiable.",
            "el recorrido de Daniela sirve también como tour del dealer: se ven todas las áreas sin tener que explicarlas.",
            "\u201cCarlos\u201d es un nombre de ejemplo: usar el nombre real de quien maneja los envíos. Confirmar a qué países envían antes de grabar; la pregunta se puede cambiar por otra duda real (título, garantía, etc.).",
            "el Plano 3 se graba en una sola toma con gimbal o celular estabilizado.",
        ],
        "hook_planos": "Planos 1–2",
        "cta_planos": "Plano 6",
    },
]
